# Bun configuration file

[test]
# Explicitly set test file patterns
root = "./tests"

# Ensure tests run in the correct environment  
smol = false

# Exclude TypeScript definition tests
exclude = ["**/*.test.ts"]